### ISSUE TITLE
tuxmake crashes while building hppa on 4.9 stable-rc kernel

### ISSUE THREAD

**Issue by bhcopeland** [kernelci/tuxmake#96]
***In GitLab by @vishalbhoj on Nov 20, 2020, 17:04 GMT:***

The kernel tree: https://gitlab.com/Linaro/lkft/mirrors/stable/linux-stable-rc/-/tree/v4.9.244

tuxmake reproducer: https://builds.tuxbuild.com/1kYGRvJMh3zeYeRdzeGymJ2cbjF/tuxmake_reproducer.sh

here is the log:
```
docker.io/tuxmake/hppa_gcc:latest
make --silent --keep-going --jobs=16 O=/root/.cache/tuxmake/builds/18/tmp ARCH=parisc CROSS_COMPILE=hppa-linux-gnu- defconfig
make --silent --keep-going --jobs=16 O=/root/.cache/tuxmake/builds/18/tmp ARCH=parisc CROSS_COMPILE=hppa-linux-gnu-
make --silent --keep-going --jobs=16 O=/root/.cache/tuxmake/builds/18/tmp ARCH=parisc CROSS_COMPILE=hppa-linux-gnu- bzImage
grep -q CONFIG_MODULES=y /root/.cache/tuxmake/builds/18/tmp/.config
make --silent --keep-going --jobs=16 O=/root/.cache/tuxmake/builds/18/tmp ARCH=parisc CROSS_COMPILE=hppa-linux-gnu- modules
make --silent --keep-going --jobs=16 O=/root/.cache/tuxmake/builds/18/tmp ARCH=parisc CROSS_COMPILE=hppa-linux-gnu- modules_install INSTALL_MOD_STRIP=1 INSTALL_MOD_PATH=/root/.cache/tuxmake/builds/18/tmp/modinstall
tar caf /root/.cache/tuxmake/builds/18/tmp/modules.tar.xz -C /root/.cache/tuxmake/builds/18/tmp/modinstall lib
test -d arch/hppa/boot/dts
# Skipping dtbs because precondition failed
make --silent --keep-going --jobs=16 O=/root/.cache/tuxmake/builds/18/tmp ARCH=parisc CROSS_COMPILE=hppa-linux-gnu- vmlinux
xz -T0 --keep /root/.cache/tuxmake/builds/18/tmp/vmlinux
Traceback (most recent call last):
  File "/usr/local/bin/tuxmake", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/tuxmake/cli.py", line 269, in main
    result = build(**build_args, auto_cleanup=(not options.shell))
  File "/usr/local/lib/python3.8/dist-packages/tuxmake/build.py", line 499, in build
    builder.run()
  File "/usr/local/lib/python3.8/dist-packages/tuxmake/build.py", line 475, in run
    self.copy_artifacts(target)
  File "/usr/local/lib/python3.8/dist-packages/tuxmake/build.py", line 389, in copy_artifacts
    shutil.copy(src, Path(self.output_dir / dest))
  File "/usr/lib/python3.8/shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/tuxmake/builds/18/tmp/arch/parisc/boot/bzImage'

```

**Assignees:** terceiro

*Migrated from GitLab: https://gitlab.com/Linaro/tuxmake/-/issues/96*

**Comment by bhcopeland** [comment]
***In GitLab by @vishalbhoj on Nov 20, 2020, 17:09 GMT:***

Seeing the issue with latest tuxmake and parisc as target_arch:
```
root@pop-os:/linux# tuxmake --runtime docker --target-arch parisc --kconfig tinyconfig
# to reproduce this build locally: tuxmake --target-arch=parisc --kconfig=tinyconfig --toolchain=gcc --wrapper=none --runtime=docker --image=tuxmake/parisc_gcc config kernel modules dtbs debugkernel
Using default tag: latest
latest: Pulling from tuxmake/parisc_gcc
Digest: sha256:3bdeb6716b20a4e2942b30e10996c06eeadfc736c21b4996d1cb6a3b5fca6fd8
Status: Image is up to date for tuxmake/parisc_gcc:latest
docker.io/tuxmake/parisc_gcc:latest
make --silent --keep-going --jobs=16 O=/root/.cache/tuxmake/builds/21/tmp ARCH=parisc CROSS_COMPILE=hppa-linux-gnu- tinyconfig
Using .config as base
Merging /linux/kernel/configs/tiny.config
Value of CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE is redefined by fragment /linux/kernel/configs/tiny.config:
Previous value: CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE=y
New value: # CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE is not set

Value of CONFIG_CC_OPTIMIZE_FOR_SIZE is redefined by fragment /linux/kernel/configs/tiny.config:
Previous value: # CONFIG_CC_OPTIMIZE_FOR_SIZE is not set
New value: CONFIG_CC_OPTIMIZE_FOR_SIZE=y

Value of CONFIG_SLUB is redefined by fragment /linux/kernel/configs/tiny.config:
Previous value: CONFIG_SLUB=y
New value: # CONFIG_SLUB is not set

Value of CONFIG_SLOB is redefined by fragment /linux/kernel/configs/tiny.config:
Previous value: # CONFIG_SLOB is not set
New value: CONFIG_SLOB=y

#
# merged configuration written to .config (needs make)
#
make --silent --keep-going --jobs=16 O=/root/.cache/tuxmake/builds/21/tmp ARCH=parisc CROSS_COMPILE=hppa-linux-gnu-
make --silent --keep-going --jobs=16 O=/root/.cache/tuxmake/builds/21/tmp ARCH=parisc CROSS_COMPILE=hppa-linux-gnu- bzImage
grep -q CONFIG_MODULES=y /root/.cache/tuxmake/builds/21/tmp/.config
# Skipping modules because precondition failed
test -d arch/parisc/boot/dts
# Skipping dtbs because precondition failed
make --silent --keep-going --jobs=16 O=/root/.cache/tuxmake/builds/21/tmp ARCH=parisc CROSS_COMPILE=hppa-linux-gnu- vmlinux
xz -T0 --keep /root/.cache/tuxmake/builds/21/tmp/vmlinux
Traceback (most recent call last):
  File "/usr/local/bin/tuxmake", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/tuxmake/cli.py", line 98, in main
    result = build(**build_args, auto_cleanup=(not options.shell))
  File "/usr/local/lib/python3.8/dist-packages/tuxmake/build.py", line 517, in build
    builder.run()
  File "/usr/local/lib/python3.8/dist-packages/tuxmake/build.py", line 493, in run
    self.copy_artifacts(target)
  File "/usr/local/lib/python3.8/dist-packages/tuxmake/build.py", line 406, in copy_artifacts
    shutil.copy(src, Path(self.output_dir / dest))
  File "/usr/lib/python3.8/shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/tuxmake/builds/21/tmp/arch/parisc/boot/bzImage'

```

**Comment by bhcopeland** [comment]
***In GitLab by @terceiro on Nov 27, 2020, 14:52 GMT:***

debugging this, from inside the build dir, I found that there is no arch/parisc/boot at all, even though there **was** a `make bzImage` during the build:

```
$ ls arch/parisc/
include  kernel  lib  math-emu  mm  oprofile
```

so it seems that this build is broken somehow. now the question is that tuxmake should fail the build, instead of crashing when it doesn't find the expected artifacts in the build directory.

**Comment by bhcopeland** [comment]
***In GitLab by @terceiro on Nov 27, 2020, 18:33 GMT:***

as for parisc: I tried 4.4 stable, with the same result as the original report. 5.9 works, so the support for actually creating a `bzImage` for parisc came at some point between 4.9 and 5.9

**Comment by bhcopeland** [comment]
***In GitLab by @terceiro on Dec 18, 2020, 14:24 GMT:***

mentioned in commit cf028e8499627a3a6934048072271e3c1a9cfc9b

**Comment by bhcopeland** [comment]
***In GitLab by @terceiro on Dec 18, 2020, 15:09 GMT:***

mentioned in commit 1aae6652468af17bb64a72c4728e7539295225b2
